name: snap_chart
description: A dead-simple Flutter charting library. Beautiful charts with minimal code. Inspired by fl_chart but designed for simplicity.
version: 1.0.1
homepage: https://github.com/rameshsambudev/easy_chart
repository: https://github.com/rameshsambudev/easy_chart
issue_tracker: https://github.com/rameshsambudev/easy_chart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
